# In The Name Of God
# ========================================
# [] File Name : Makefile
#
# [] Creation Date : 09-04-2016
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================

.PHONY: all
all: related

related: related.tex
	xelatex related.tex
